# Generated by Django 5.2.8 on 2025-11-09 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_remove_pedido_cliente_remove_pedido_producto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la promo')),
                ('descripcion', models.TextField(verbose_name='Descripción corta')),
                ('imagen', models.ImageField(upload_to='promos/', verbose_name='Banner o foto')),
                ('etiqueta', models.CharField(help_text="Ej: '2x1', '-15%', 'Oferta'", max_length=50)),
                ('enlace_categoria', models.CharField(choices=[('vitrina', 'Vitrina'), ('tortas', 'Tortas'), ('postres', 'Postres')], max_length=50, verbose_name='Enlace a categoría')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Está activa?')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('vitrina', 'Repostería de vitrina'), ('tortas', 'Tortas'), ('postres', 'Postres')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Mostrar en inicio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pagado', max_length=20)),
                ('tipo_entrega', models.CharField(choices=[('retiro', 'Retiro en tienda'), ('despacho', 'Despacho a domicilio')], default='retiro', max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='adminpanel.pedido')),
            ],
        ),
    ]
