# Generated by Django 5.2.8 on 2025-11-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_promocion_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='descuento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='vigencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
